### ISSUE TITLE
Problem with BCU-java-PC java/common dependencies

### ISSUE THREAD

**Issue by ramen-cat-coder** [battlecatsultimate/BCU-java-PC#109]
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/d5e4bc54-d339-4c3f-9000-74631476dbad)
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/0c01d039-d5a1-4cee-8aa0-bda9b18d39d5)

Common is having a lot of issues detecting nearly all dependencies, despite attempts to import them.
All configuration seems to be proper in the project settings. I have already tried invalidate cache.

**Comment by iREDMe** [comment]
I believe this is because the compiler in the settings is set to "Javac" when it should be "Eclipse"

**Comment by ramen-cat-coder** [comment]
Yeah, that fixed it...
