### ISSUE TITLE
BCU shader and JOGL failure

### ISSUE THREAD

**Issue by ramen-cat-coder** [battlecatsultimate/BCU-java-PC#110]
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/895fa475-cf8c-4371-b010-e864ae1439a4)

Yeah I'm opening an issue again...
This isnt a bug in the program but I've been hacking at this for a good while and have not been able to resolve it in any way

At this point I am absolutely dumbfounded about what the issue could be here, all of the information I've found online is too vague to be useful

Also the JAR compiles to be worryingly small and returns the same error when I try and run it with command line, and does not do anything else afterwards (no window or anything at all)

The same problem affects the BCU-Initializer artifact

I suspect that the java root of the project is not being put inside of the JAR, but I'm not sure how to fix that either
IntelliJ's UI is very confusing to me so I am worried I made a really really dumb mistake here

**Comment by iREDMe** [comment]
Yea problems can get extremely confusing, try some of these ideas:
1. Run `Rebuild Project` (under `Build` in the menu bar)
2. Make sure `src/main/java` is the only Source folder, `src/main/resources` is the only Resource folder, and `target` is the only Excluded folder (in Project Settings -> Modules)
3. Make sure the SDK is set to 1.8 and the Language Level set to 8

If none of these work, then I honestly don't know, but I can probably look into it a bit more

**Comment by ramen-cat-coder** [comment]
Yeah.. same problem
Tried rebuilding and setting the resources folder (which I forgot to set already, lol) as well as ensuring the source, but it's still improper 
Do you need a screenshot of my artifacts' settings?

**Comment by ramen-cat-coder** [comment]
The problem could be though that the main root is not in the classpath?
But I don't know how to put it in if that _is_ the issue

**Comment by iREDMe** [comment]
If it's only affecting running the jar itself, yes, screenshots of the artifact settings would help. You don't need to build the jar to run/compile BCU, but I assume that this is the end goal at the moment.

We have a video on how to properly make an artifact, I'll see about being able to share that video (and if not, i'll say how to do it in text form)

**Comment by ramen-cat-coder** [comment]
The error occurs when running MainBCU from IntelliJ IDEA as a test run so compilation isn't truly the end goal here

**Comment by iREDMe** [comment]
Oh, that's weird.

Just to confirm, this is what you see on your side, right?

![Screenshot 2024-05-18 at 11 56 43 PM](https://github.com/battlecatsultimate/BCU-java-PC/assets/43896697/c1061479-fcdd-40e8-a342-e77dfeb842d0)
![Screenshot 2024-05-18 at 11 56 50 PM](https://github.com/battlecatsultimate/BCU-java-PC/assets/43896697/93e15576-27cf-482a-a63a-ced260a8b8e5)

If this is all good and done, and Eclipse is the compiler (sometimes IntelliJ does a bad and randomly resets things for no reason), then I really am not sure. Maybe try Invalidating Caches?

**Comment by ramen-cat-coder** [comment]
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/e1a43958-6a56-43fb-96d3-327057f560a1)
This is my version.
The problem in the Problems tab is this: 
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/6fcf3720-214d-416c-8345-50a1cb42dc18)

**Comment by iREDMe** [comment]
MMmmm yup I've got no idea, sorry. Maybe @MandarinSmell knows something about this? (I actually have no idea if this "pings" him or not, but we'll see)

**Comment by MandarinSmell** [comment]
This is more of IDE problem, not BCU's project file. This can be resolved by rebuilding project, invalidating cache, or recreating profile

**Comment by ramen-cat-coder** [comment]
Tried invalidating cache, but it cause this error, which I can't fix because I can't import this (Can't find, can't load with intellij)
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/b497c637-d12e-4281-a5d8-e6b9577bd2de)

**Comment by MandarinSmell** [comment]
That's again IDE's problem (IDE not being able to recognize third party library). Rerun maven, or rebuild project

**Comment by ramen-cat-coder** [comment]
library problem has been solved

**Comment by ramen-cat-coder** [comment]
BCU now launches in IntelliJ

**Comment by ramen-cat-coder** [comment]
nevermind,
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/3f4de52b-bc9b-43c3-8794-b719781e9426)

Failed to get resource : jogl/util/shader/120.vp


It also crashes when viewing animations, lineups:
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/3155f86f-5086-48bd-b8c5-9af87bc8dbdd)

**Comment by ramen-cat-coder** [comment]
I assume this always happens in IntelliJ
The error has to do with lang files

**Comment by MandarinSmell** [comment]
This isn't problem of the code, but your PC's hardware status. BCU uses OpenGL 1.2 or 1.3 to support as many devices as possible. Not being able to run OpenGL (Library is JOGL) means your hardware doesn't support OpenGL 1.X due to whatever reason, or you didn't install proper graphic driver

This isn't something that we can't help much because it's not problem of the code

Also open other issue rather than reusing same post if it's about different problem

**Comment by ramen-cat-coder** [comment]
Oh, okay

But BCU works normally for me without IntelliJ,.
