### ISSUE TITLE
BCU can't access files on build

### ISSUE THREAD

**Issue by ramen-cat-coder** [battlecatsultimate/BCU-java-PC#111]
Errors and fails to load JOGL shaders, animations, and language files.

BCU works completely fine on release builds, but on builds built with IntelliJ artifacts, they have file problems.

*could be a library issue? But I'm not certain which it could be.

**Comment by MandarinSmell** [comment]
You have to write class path properly, otherwise it won't work

**Comment by ramen-cat-coder** [comment]
I'll try that

**Comment by ramen-cat-coder** [comment]
Is this proper?
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/6de7f26c-9472-43aa-ad73-cae5ead01cb9)

**Comment by MandarinSmell** [comment]
For us, we used space separator for MANIFEST.MF file. I doubt it will bring any difference tho. However, considering BCU failing to load resource files, jar file may not contain resource files, and maybe that's the cause of problem. Also adding such class path means external libraries must be contained as jar files in said path, so make sure required files are all prepared properly

**Comment by MandarinSmell** [comment]
Check if resource folder is marked properly, and your artifact puts resource files together into jar file as well

**Comment by ramen-cat-coder** [comment]
Is it correct that the main jar has the manifest located in `src\main\META-INF\MANIFEST.MF` ?
As shown.
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/50137eb3-7afb-41b9-b3ae-caac9f9df1bc)

**Comment by MandarinSmell** [comment]
> Errors and fails to load JOGL shaders, and language files.

This means jar file has failed to grab resource file, and this is what I just suggested above

> animations,

It's obvious error that caused by shader not being loaded. BCU tries to create `Program` ([glCreateProgram](https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glCreateProgram.xml)), and it will try to attach shader ([glAttachShader](https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glAttachShader.xml)) to it. Since jar file has failed to get shader file from resource, BCU will fail to create program, leading to crash

**Comment by MandarinSmell** [comment]
> Is it correct that the main jar has the manifest located in `src\main\META-INF\MANIFEST.MF` ?

We have put it in `./src/META-INF/` folder. It's due to wonky behavior or IntelliJ IDEA, what it puts as default is `./src/resources/META-INF/`

**Comment by ramen-cat-coder** [comment]
Okay.
I would also like to know: is src\main\resources the right spot to set resource folder?

**Comment by MandarinSmell** [comment]
Yes, that's where IDEA project initializer creates as default

**Comment by ramen-cat-coder** [comment]
The resource files are in the root directory of the jar: these ones.
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/5c524c1b-3073-4d15-b8b1-118d12bf1e7f)

JAR contents:
![image](https://github.com/battlecatsultimate/BCU-java-PC/assets/124401935/bd0735f3-c536-44fe-8207-b9864a34f14e)

**Comment by MandarinSmell** [comment]
If jar file still shows error, at least it should have created error log in `logs` folder. Read stacktrace in there. There's not much that we can help now

**Comment by ramen-cat-coder** [comment]
The classpath only includes files from `BCU_lib`. Could that be a classpath issue?

**Comment by MandarinSmell** [comment]
class path is group of paths that jar file can link other classes to. It's used for connecting separated 3rd party libraries (as form of jar file) into main jar file. It doesn't perform more job than that

**Comment by ramen-cat-coder** [comment]
Ah..... I don't think it's within my ability or my IDE's ability to solve this, so..

**Comment by ramen-cat-coder** [comment]
Fixed it. Something was wrong, no idea what, but cloning it without the terminal worked
