### ISSUE TITLE
[Suggestion] Duplicate Units

### ISSUE THREAD

**Issue by IceandFire04** [battlecatsultimate/BCU-java-PC#114]
Please add a little button to duplicate units from either your pack ore from the base game. This would be useful for things like adding different forms with similar/identical stats.

**Comment by iREDMe** [comment]
You should already be able to copy stats from custom/base game into custom cats/enemies. If I recall, on the editing page, there should be an `import` button for copying stats of the corresponding cat or enemy, then a `units` or `enemies` button for stats of the opposing side.

**Comment by IceandFire04** [comment]
wow im blind
