### ISSUE TITLE
what to do after Update complete. use EXAMPLE:BCU0-5-47-0 for now on.

### ISSUE THREAD

**Issue by ModGamerBackup** [battlecatsultimate/BCU-java-PC#63]
idk what to do can you help me

**Comment by ModGamerBackup** [comment]
i am sorry if rude or spamming or whatever not good

**Comment by ModGamerBackup** [comment]
if you block me from repository i will just be mad

**Comment by ModGamerBackup** [comment]
why does it keep reseting my data why devil bee I think = rip

**Comment by MandarinSmell** [comment]
1. If you don't want to be blocked from our repo, __stop acting like a child__. Show us that you can create decent and serious discussion to solve your problem. Be cooperative to us, so we can analyze what things are happening. __Stop sending comment like chatting, be as detailed as possible whenever you want to ask something.__

2. For now, you didn't specify what exact data you want to save. Tell us what you want to achieve, and what you have tried to achieve it.

3. Your first comment might make me misunderstand, but BCU isn't something like game. It doesn't have goal, or required things to do. It's simulator or sandbox utility program, you have to find what you want to do with it.

I will say again, stop acting like child, and give us proper information about your problem, or we can't and won't help you

**Comment by ModGamerBackup** [comment]
I want to achieve devil bee for bcu aku shield

**Comment by ModGamerBackup** [comment]
1:i maked the devil bee spritesheat from bbu/battle bees ultimate
2: import it using cow cat
Not done 3: Aku Shield i mean we do have barriers but why can't it respawn like aku shields?

**Comment by ModGamerBackup** [comment]
Here is bbu
![Uploading Screenshot_20211015_041728.jpg…]()

**Comment by ModGamerBackup** [comment]
![Screenshot_20211015_041823](https://user-images.githubusercontent.com/82563453/137389398-922eae70-5379-4316-8042-8cb488fd4d7e.jpg)

**Comment by ModGamerBackup** [comment]
![Screenshot_20211015_041728](https://user-images.githubusercontent.com/82563453/137389440-393bdf64-c8f0-4263-88e2-5b503c2e83e9.jpg)

**Comment by ModGamerBackup** [comment]
The devil bee is the blue bee thede

**Comment by ModGamerBackup** [comment]
There

**Comment by Xerpyy** [comment]
This is not a place to chat, this exists to report possible Bugs and Issues with BCU itself.
If you want to chat with people consider joining the discord.

**Comment by ModGamerBackup** [comment]
I cant idk what is pass

**Comment by Xerpyy** [comment]
Read the rules for the password.

**Comment by ModGamerBackup** [comment]
What rules link pls

**Comment by Xerpyy** [comment]
I will not help you further with finding the password. Please avoid chatting here in the future if you are not here to report Bugs and Issues.
