### ISSUE TITLE
help about bluestacks

### ISSUE THREAD

**Issue by ijustcamehereforbcu** [battlecatsultimate/BCU-java-PC#65]
hello,
i need help with how to open the file. i'm using bluestacks and have the file downloaded, but when i try to open it, it just says "cant open file". any ideas why this is happening? thanks!

**Comment by ghost** [comment]
Why would you use an android emulator to open up BCU when you can literally just get the PC version lmao

**Comment by ijustcamehereforbcu** [comment]
i legit dont know ive never used this
thanks anyway

**Comment by ijustcamehereforbcu** [comment]
k so i went thru and checked every link and it gives me the same issue, both in my normal browser and in bluestacks and got the same answer
idk at this point ig theres something clear i just dont see
sorry i keep interrupting yall

**Comment by ModAltForBCUandBBU** [comment]
PC VERSION does not support android or bluestacks only BCU ANDROID use that

**Comment by ModAltForBCUandBBU** [comment]
this needs to bee closed

**Comment by iREDMe** [comment]
You should be running the BCU jar on your desktop. Keep in mind BCU is not something that affects the Battle Cats app.
