### ISSUE TITLE
how do i animate

### ISSUE THREAD

**Issue by ModAltForBCUandBBU** [battlecatsultimate/BCU-java-PC#66]
i promise i wont act as a kid now
How do i animate? i used this spritesheet to
![costume1 (1)](https://user-images.githubusercontent.com/93238229/138994563-5e9cfaa7-71f5-4c71-a680-551f9f45ae1d.png)
made in scratch
how do i make Mamodel? how can i make it play the knockback animation or attacl animation? can somebody help me i even read the how to animate and there was no How to play attack animation

**Comment by ModAltForBCUandBBU** [comment]
here is the spritesheet contents
![spritesheet](https://user-images.githubusercontent.com/93238229/138994914-c5e1aa82-5fc2-43eb-848e-367a0e3f4fc6.JPG)

**Comment by ModAltForBCUandBBU** [comment]
i want to make magic bee for no reason his abilities are Magic Shield because he is a magic bee or Magican Bee

**Comment by iREDMe** [comment]
GitHub Issues is not your personal help for how to use certain features, such as animating, of BCU. Please read the BCU Animation Guide linked in the README.
