### ISSUE TITLE
File not opening properly when double clicked.

### ISSUE THREAD

**Issue by Pairless** [battlecatsultimate/BCU-java-PC#69]
The default program to open it with is Java(TM) Platform SE Binary and when I open it, it opens a command bar with the Java logo in the top left corner, before disappearing fractions of a second later. Nothing else has happened other than this, but when I clicked it, it didn't close, but there was nothing I could do with it so I closed it.
TL;DR: BCU not opening properly

Edit: When I tried to type something in the box, the window just completely disappeared.

**Comment by MandarinSmell** [comment]
Did you download BCU-Initializer? Create folder (name doesn't matter), and put BCU-Initializer into that newly created folder. And put folder to Desktop. When you run it, it should be opened properly.

If `command bar` you saying means prompt windows, then you can try to reinstall Java. Remove all Java via control panel, and download Java in link below : 

https://www.java.com/en/download/manual.jsp

Be aware that you have to consider OS type when you download Java (aka JRE). For example, if you are using Windows 64bit, you have to download `Windows Offline (64bit)` one. I don't know if Online one can consider OS type, but as far as I know it can't, so you have to download offline one.

Next thing to say is that, if you are using Windows, never use `Open With` option. You must be able to open jar file by simple double clicks. If something zip archive program opened when you double click it, follow steps below

1. Click jar file (BCU-Initializer) **once**
2. Right click jar file
3. Click `Properties`
4. Click `Change...` next to `Open with`
5. Program list will appear. Select Java
6. Click `Apply` and `OK`
7. Try to run BCU by double clicking it

If problem still exists and you are using Windows, next solution you can try is using Jarfix. Jarfix can register proper Java to the system, so you can make jar file opened with correct Java. This isn't virus or any harmful program, so you can download and open it with no worries. Link is below : 

https://johann.loefflmann.net/en/software/jarfix/index.html

**Comment by Pairless** [comment]
> Did you download BCU-Initializer? Create folder (name doesn't matter), and put BCU-Initializer into that newly created folder. And put folder to Desktop. When you run it, it should be opened properly.
> 
> If `command bar` you saying means prompt windows, then you can try to reinstall Java. Remove all Java via control panel, and download Java in link below :
> 
> https://www.java.com/en/download/manual.jsp
> 
> Be aware that you have to consider OS type when you download Java (aka JRE). For example, if you are using Windows 64bit, you have to download `Windows Offline (64bit)` one. I don't know if Online one can consider OS type, but as far as I know it can't, so you have to download offline one.
> 
> Next thing to say is that, if you are using Windows, never use `Open With` option. You must be able to open jar file by simple double clicks. If something zip archive program opened when you double click it, follow steps below
> 
> 1. Click jar file (BCU-Initializer) **once**
> 2. Right click jar file
> 3. Click `Properties`
> 4. Click `Change...` next to `Open with`
> 5. Program list will appear. Select Java
> 6. Click `Apply` and `OK`
> 7. Try to run BCU by double clicking it
> 
> If problem still exists and you are using Windows, next solution you can try is using Jarfix. Jarfix can register proper Java to the system, so you can make jar file opened with correct Java. This isn't virus or any harmful program, so you can download and open it with no worries. Link is below :
> 
> https://johann.loefflmann.net/en/software/jarfix/index.html

I managed to fix it by putting in "java -jar (directory to file).jar" in the command bar and it worked, also great app by the way

**Comment by MandarinSmell** [comment]
That's little bit tedious way. Even though the solution I suggested looks more tedious, but once you finish these steps, you won't need to run `java -jar [BCU jar name]` manually every time when you try to run it. You will be able to open jar file by simply double clicking. Also when update will be released, then you will also need to chance that `(directory to file)` you mentioned, becoming more tedious

**Comment by MandarinSmell** [comment]
Close the issue if you think problem is solved, or you can handle it. I will leave this issue opened for 3 days. If there will be no further answers, then I will close the issue

**Comment by Pairless** [comment]
> That's little bit tedious way. Even though the solution I suggested looks more tedious, but once you finish these steps, you won't need to run `java -jar [BCU jar name]` manually every time when you try to run it. You will be able to open jar file by simply double clicking. Also when update will be released, then you will also need to chance that `(directory to file)` you mentioned, becoming more tedious

I don't want to download any random stuff on my PC, and there's no problem with me doing it, so I'm just going to keep using the command bar.
