### ISSUE TITLE
the enemy filter. thats all.

### ISSUE THREAD

**Issue by saeedo111** [battlecatsultimate/BCU-java-PC#78]
I chose some OR operations for some enemies but now I want it to be the normal enemy list again. I click everywhere, nothing works. can you please show me a way to get te normal enemy list again?

**Comment by MandarinSmell** [comment]
You can just exit enemy list, and re-enter it. Or, if you want to unselect the stuffs that you selected before, hold Ctrl key, and click lists again

**Comment by saeedo111** [comment]
thanks :D
