### ISSUE TITLE
LAG.

### ISSUE THREAD

**Issue by saeedo111** [battlecatsultimate/BCU-java-PC#80]
Actual issue this time. Every time I playtest my stage, it runs like its being played on a potato! I mean, the level only contains a 9000% buffed hippoe and a 9000% buffed kang roo! Please, tell me the fix to this! I closed the program and opened it again and nothing changed! Why is this happening?

**Comment by MandarinSmell** [comment]
Go to BCU config and turn on JOGL, that will reduce lags

**Comment by saeedo111** [comment]
ok i will try
