### ISSUE TITLE
The latest BCU are missing part of or all of 12.1 content

### ISSUE THREAD

**Issue by tzwasd** [battlecatsultimate/BCU-java-PC#90]
When I browse unit datas, filter them by "Stop Wave", there's no "暗黒の精霊王ヤミノワールド" (true form of Yamii), which should be added by BC 12.1 .

![Screenshot_20230301_204125](https://user-images.githubusercontent.com/68690643/222142915-b702b894-a98e-460a-ad04-3f7aa1e0c0fb.png)

And I found the stat page of Yamii, it missed true form as well.

![Screenshot_20230301_204148](https://user-images.githubusercontent.com/68690643/222142931-3b7f4c71-0e42-464c-996f-41f54ebbd6e0.png)

I try to reinstall BCU by delete all of files except BCU-Initializer.jar and re-run it (~~it shows 12.1 content have been download~~), nothing changes.

**Comment by MandarinSmell** [comment]
That's simply because we didn't add 12.1 data to BCU. Wait for update

**Comment by tzwasd** [comment]
> That's simply because we didn't add 12.1 data to BCU. Wait for update

Thanks for reply, I wrongly thought 12.1 have been added because I saw this commit dc8b8bf3eea9b97bb52998743ac026dc0dd6988b

**Comment by tzwasd** [comment]
PS: if BCU can show what's the BC data version in it, that will be good.
