### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by Stronkkey** [battlecatsultimate/BCU-java-PC#98]
One of the tips you can get when starting up the program is: 

> _This program is completely free to use and open-source. If you paid for this, you got scammed_

Problem is that there is neither a License file nor any copyright info attached to the code.

**Comment by MandarinSmell** [comment]
I doubt they would keep the rules of license even though we add proper license to the program, or copyright as well. Also it's bit complicated situation to add our "own" license or copyright to this program, can't tell that in details, but we are aware of this

Most of all, these scamming sellers sell already generated .jar file which doesn't reveal raw codes. The tip itself already clearly says that this program is shared freely, so users aren't supposed to pay this program, so we'd say that will be enough

**Comment by MandarinSmell** [comment]
Closing issue due to discontinued discussion
