### ISSUE TITLE
[Feature Request] a new button in CustomStage page which can export a stage data to a csv file

### ISSUE THREAD

**Issue by Areaslky** [battlecatsultimate/BCU-java-PC#99]
As mentioned, I requested a new button in the CustomStage interface to facilitate exporting the Stage as .csv file that can be read by BC.
  **Here are my reasons**
  I am a BC Mod developer and the reason for requesting this feature is that I need a lot of time to edit the Stage file to make the mod.
  So I hope to add this functionality to the bcu to avoid unnecessary errors when editing stages and to reduce the time required.
  
  **Detailed requirements**
  Add a button in the blank space of this interface, using it will bring up a window to facilitate the user to name the exported file.
Click OK after naming, the file will be exported as .csv file with the same format as BC, and can be read directly by bc.
  
![$5G4 %NO{OAD{ASCF{E(}A1](https://github.com/battlecatsultimate/BCU-java-PC/assets/141044550/c32b5fcc-6a9f-4969-a04c-d6108c89d546)

The exported file will be stored in the "CSV" folder under the bcu directory. The exported file does not need to contain music, etc., but only needs to contain the content that should be contained in the stage.csv file
For example: bg, ememy, castle, Enemy Limit, length, etc. (same as level files in bc)

**Comment by MandarinSmell** [comment]
We won't add any features that *help* users through modding the BC. We are trying to stay BCU as BCU, no more than that. We can't catch Ponos' eyes more, with the fact that it already can be taken down if they ever wanted to. We request you not to suggest features like this

Thus closing the issue
